/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * MessageTemplateAPI
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export interface MessageTemplateRequest {
  templateContent?: string;
  description?: string;
}
